repos:
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.5.0
  hooks:
  - id: nbqa-pyupgrade
    args: ["--py36-plus"]
  - id: nbqa-black
  - id: nbqa-flake8
  - id: nbqa-isort
    args: ["--profile=black"]
