repos:
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.2.3
  hooks:
  - id: nbqa-pyupgrade
    args: ["--py36-plus"]
  - id: nbqa-black
  - id: nbqa-flake8
    args: ["--max-line-length=88", "--extend-ignore=E203"]
  - id: nbqa-isort
    args: ["--profile=black"]
