name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  python-lint-format:
    uses:
      sgibson91/.github/.github/workflows/python-lint-format.yaml@main

  clean-notebooks:
    uses:
      sgibson91/.github/.github/workflows/clean-notebook-outputs.yaml@main
