name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  clean-notebooks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Ensure Clean Jupyter Notebooks
        uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1

  format-notebooks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Install Python 3.8
        uses: actions/setup-python@master
        with:
          python-version: 3.8

      - name: Install black-nb
        run: |
          python -m pip install --upgrade pip
          pip install black-nb==0.4.0

      - name: Check Notebooks
        run: |
          black-nb --check .
