name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  clean-notebooks:
    uses:
      sgibson91/.github/.github/workflows/clean-notebook-outputs.yaml@main
